name: cmake-continuous-integration

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    strategy:
      matrix:
        os: ['windows-latest']
        toolchain:
          - 'msvc-amd64'
          - 'msvc-arm64'
          - 'msvc-x86'
          # - 'clang-msvc-amd64'
          # - 'clang-msvc-arm64'
          # - 'clang-msvc-x86'
        config:
          - 'Debug'
          - 'Release'
        generator:
          - 'Ninja'
          # - 'Visual Studio 17 2022'
    runs-on: ${{ matrix.os }}
    name: ${{ matrix.config }} ${{ matrix.toolchain }}
    # name: ${{ matrix.config }} ${{ matrix.toolchain }} ${{ matrix.generator }}
    steps:
    - uses: actions/checkout@v4
    - name: Install Nuget Packages
      run: nuget restore .\packages.config -PackagesDirectory .\packages\
    - name: Build Tools
      shell: cmd
      working-directory: ${{github.workspace}}
      run: build\build_tools.cmd
    - name: Generate
      shell: cmd
      working-directory: ${{github.workspace}}
      run: build\build_cmake.cmd "${{ matrix.generator }}" ${{ matrix.config }} ${{ matrix.toolchain }} generate
    - name: Build
      shell: cmd
      working-directory: ${{github.workspace}}
      run: build\build_cmake.cmd "${{ matrix.generator }}" ${{ matrix.config }} ${{ matrix.toolchain }} build
